swagger: '2.0'
info:
  title: 服务端API
  description: 对接H5或者APP
  version: v1
host: localhost:9000
schemes:
  - http
basePath: /v1
produces:
  - application/json
#securityDefinitions:
#  bearer:
#    type: "apiKey"
#    name: "Authorization"
#    in: header
tags:
  - name: Auth
    description: 授权
  - name: Codes
    description: 短信验证码
  - name: Images
    description: 图片上传
  - name: Users
    description: 用户

paths:
  '/auth':
    post:
      summary: 获取授权token
      consumes:
         - application/json
      parameters:
        - name: auth
          in: body
          description: 用户信息.
          required: true
          schema:
              $ref: '#/definitions/Auth'
      tags:
        - Auth
      responses:
        200:
          description: 服务器正常返回
          schema:
            $ref: '#/definitions/Token'

  '/users':
    post:
      summary: 注册用户
      consumes:
        - application/json
      parameters:
        - name: user
          in: body
          description: 用户信息
          required: true
          schema:
            $ref: '#/definitions/User'
      tags:
        - Users
      responses:
        '201':
          description: 注册成功

  '/users/{id}':
    get:
      summary: 获取用户信息
      consumes:
        - application/json
      parameters:
        - name: id
          in: path
          description: 用户id
          type: string
          required: true
      tags:
        - Users
      responses:
        '200':
          description: 注册成功
          schema:
            $ref: '#/definitions/User'

definitions:

  User:
    type: object
    properties:
      phoneNumber:
        type: string
        description: 手机号码
      password:
        type: string
        description: 密码
      code:
        type: string
        description: 短信验证码
      channel:
        type: string
        description: 渠道代码
    required:
      - phoneNumber
      - password
      - code
      - channel
    example:
      phoneNumber: "18955555555"
      password: "justPass"
      code: "666666"
      channel: wQSDOs8
  Auth:
    type: object
    properties:
      phoneNumber:
        type: string
        description: 手机号码
      password:
        type: string
        description: 密码
    required:
      - phoneNumber
      - password
    example:
      phoneNumber: "18955555555"
      password: "justPass"

  Token:
    type: object
    properties:
      token:
        type: string
        description: 返回的token
      userId:
        type: integer
        format: int64
        description: 用户id
      userName:
        type: string
        description: 用户名
    example:
      token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MywiZXhwIjoxNDcwODI5NDk1LCJ1c2VyIjp7ImlkIjozLCJwYXNzd29yZCI6IjgxY2UyYmRjMTdlMjVmNWY0MjcyMWY1ZjEzYWU5NTYwODBjNzMzOGM4ZGYwODk2OTA4MDY5MzhmNmM3MjAyODEiLCJzYWx0IjoiNTRhOTQ0ZWUtZDRkYy00ZjcyLWE2N2EtNzBiZTE4ZDc3MjMxIiwicGhvbmVOdW1iZXIiOiIxOTk5OTk5OTk5IiwiY3JlYXRUaW1lIjpudWxsLCJ1cGRhdGVUaW1lIjpudWxsLCJwZXJzaXN0ZW50Ijp0cnVlLCJlbnRpdHlJZCI6M30sImlhdCI6MTQ3MDgyNTg5NX0.kwoSodGxS81HPWCiIydk0Z4Of6rljkR6hLAQ1VNeYhs"
      userId: 100
      userName: "18955555555"

  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
        description: 参见 `ErrorCode` 中的定义
      message:
        type: string
        description: 错误描述
      detail:
        type: string
        description: 错误的详细信息
parameters:
  accessKeyIdParam:
    name: access_key_id
    in: query
    description: 访问密钥
    required: true
    type: string
  signatureVersionParam:
    name: signature_version
    in: query
    description: '签名函数的版本号,目前只支持版本号为 `1`,签名所用哈希算法为HmacSHA256'
    required: true
    type: number
    format: int32
    default: 1
  signatureParam:
    name: signature
    in: query
    description: 请求消息的签名
    required: true
    type: string
